version: 1

policies:
  - id: pcl-rustic-policy
    repo: pcl-rustic
    users:
      - hernandor

access_control:
  - resource: gpu-runner
    policies:
      - pcl-rustic-policy
  - resource: cpu-runner
    policies:
      - pcl-rustic-policy
